#ifndef PROMETHEUSENDLINETESTERLIB_GLOBAL_H
#define PROMETHEUSENDLINETESTERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROMETHEUSENDLINETESTERLIB_LIBRARY)
#  define PROMETHEUSENDLINETESTERLIB_EXPORT Q_DECL_EXPORT
#else
#  define PROMETHEUSENDLINETESTERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // PROMETHEUSENDLINETESTERLIB_GLOBAL_H
